# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-versions:
          - 3.6
          - 3.7
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v2

      - name: Setting up python ${{ matrix.python-versions }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
          architecture: x64

      - name: Creating a virtualenv python ${{ matrix.python-versions }}
        run: python -m venv .env

      - name: Installing project
        run: .env/bin/pip install -Ue ".[develop]"

      - name: Running tests
        run: .env/bin/pytest --color=yes -vv tests.py

  tests-windows:
    strategy:
      fail-fast: false

      matrix:
        python-versions:
          - 3.6
          - 3.7
          - 3.8
          - 3.9

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up python ${{ matrix.python-versions }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
          architecture: x64

      - name: Creating a virtualenv python ${{ matrix.python-versions }}
        run: python -m venv .env
        shell: cmd

      - name: Installing project
        run: .env\Scripts\pip.exe install -Ue ".[develop]"
        shell: cmd

      - name: Running tests
        run: .env\Scripts\pytest.exe --color=yes -vv tests.py
        shell: cmd
